version: '2'

services:
  tomcat:
    image: bitnami/tomcat
    ports:
      - '8080:8080'
    environment:
      - TOMCAT_USERNAME=admin
      - TOMCAT_PASSWORD=password
      - TOMCAT_ALLOW_REMOTE_MANAGEMENT=1 